# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: M:/Work/Github/ZyboExperiments.git/trunk/zcu102_bram_test/bram_test.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0.xci
# IP: The module: 'design_1_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: m:/Work/Github/ZyboExperiments.git/trunk/zcu102_bram_test/bram_test.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_1/bd_afc3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: m:/Work/Github/ZyboExperiments.git/trunk/zcu102_bram_test/bram_test.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: M:/Work/Github/ZyboExperiments.git/trunk/zcu102_bram_test/bram_test.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0.xci
# IP: The module: 'design_1_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: m:/Work/Github/ZyboExperiments.git/trunk/zcu102_bram_test/bram_test.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_1/bd_afc3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: m:/Work/Github/ZyboExperiments.git/trunk/zcu102_bram_test/bram_test.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
