-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity top_top_stream_stbkb_rom is 
    generic(
             dwidth     : integer := 5; 
             awidth     : integer := 7; 
             mem_size    : integer := 66
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of top_top_stream_stbkb_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 => "01010", 1 => "01011", 2 => "01100", 3 => "01101", 4 => "01110", 
    5 => "01111", 6 => "10000", 7 => "10001", 8 => "10010", 9 => "10011", 
    10 => "10100", 11 => "01010", 12 => "01011", 13 => "01100", 14 => "01101", 
    15 => "01110", 16 => "01111", 17 => "10000", 18 => "10001", 19 => "10010", 
    20 => "10011", 21 => "10100", 22 => "01010", 23 => "01011", 24 => "01100", 
    25 => "01101", 26 => "01110", 27 => "01111", 28 => "10000", 29 => "10001", 
    30 => "10010", 31 => "10011", 32 => "10100", 33 => "01010", 34 => "01011", 
    35 => "01100", 36 => "01101", 37 => "01110", 38 => "01111", 39 => "10000", 
    40 => "10001", 41 => "10010", 42 => "10011", 43 => "10100", 44 => "01010", 
    45 => "01011", 46 => "01100", 47 => "01101", 48 => "01110", 49 => "01111", 
    50 => "10000", 51 => "10001", 52 => "10010", 53 => "10011", 54 => "10100", 
    55 => "01010", 56 => "01011", 57 => "01100", 58 => "01101", 59 => "01110", 
    60 => "01111", 61 => "10000", 62 => "10001", 63 => "10010", 64 => "10011", 
    65 => "10100" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem : signal is "select_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem : signal is "distributed";

begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity top_top_stream_stbkb is
    generic (
        DataWidth : INTEGER := 5;
        AddressRange : INTEGER := 66;
        AddressWidth : INTEGER := 7);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of top_top_stream_stbkb is
    component top_top_stream_stbkb_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    top_top_stream_stbkb_rom_U :  component top_top_stream_stbkb_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


