webtalk_init -webtalk_dir /home/hbucher/tests/xilinx/zybo_hls_maxi_test/zybo_hls_maxi_test.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-01-25 02:48:07" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "208020568_1777516090_210627092_404" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2a4j3gqooe7mnil07384k3jtd8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2234.171 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.252 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1516625358000" -context "sdk\\\\bsp/1516625358000"
webtalk_add_data -client sdk -key hwid -value "1516624724000" -context "sdk\\\\bsp/1516625358000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1516625358000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1516625358000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1516625358000"
webtalk_add_data -client sdk -key uid -value "1516625360000" -context "sdk\\\\application/1516625360000"
webtalk_add_data -client sdk -key hwid -value "1516624724000" -context "sdk\\\\application/1516625360000"
webtalk_add_data -client sdk -key bspid -value "1516625358000" -context "sdk\\\\application/1516625360000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1516625360000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1516625360000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1516625360000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1516625360000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1516625360000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1516625360000"
webtalk_add_data -client sdk -key projSize -value "209.8984375" -context "sdk\\\\application/1516625360000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1516870087382"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1516870087382"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1516870087382"
webtalk_add_data -client sdk -key DebugCount -value "31" -context "sdk\\\\bsp/1516870087382"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1516870087382"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1516870087382"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1516870087382"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1516870087382"
webtalk_transmit -clientid 212189011 -regid "208020568_1777516090_210627092_404" -xml /home/hbucher/tests/xilinx/zybo_hls_maxi_test/zybo_hls_maxi_test.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/hbucher/tests/xilinx/zybo_hls_maxi_test/zybo_hls_maxi_test.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/hbucher/tests/xilinx/zybo_hls_maxi_test/zybo_hls_maxi_test.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
