# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: M:/Work/Github/ZyboExperiments.git/trunk/zcu102_bram_test/bram_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0.xci
# IP: The module: 'design_1_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: m:/Work/Github/ZyboExperiments.git/trunk/zcu102_bram_test/bram_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_1/bd_f60c.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c || ORIG_REF_NAME==bd_f60c}]

# XDC: m:/Work/Github/ZyboExperiments.git/trunk/zcu102_bram_test/bram_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_1/bd_f60c_ooc.xdc

# IP: M:/Work/Github/ZyboExperiments.git/trunk/zcu102_bram_test/bram_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0.xci
# IP: The module: 'design_1_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: m:/Work/Github/ZyboExperiments.git/trunk/zcu102_bram_test/bram_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_1/bd_f60c.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f60c || ORIG_REF_NAME==bd_f60c}]

# XDC: m:/Work/Github/ZyboExperiments.git/trunk/zcu102_bram_test/bram_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_1/bd_f60c_ooc.xdc
